const Colors = {
  GAME_BACKGROUND:"#1a1a1a",
  TITTLE_GAME:'#FFF',
  SQUARE_KEYBOARD_BACKGROUND:"#949494",
  SQUARE_KEYBOARD:'#FFF',
  TOAST_LABEL: '#FFF',
  WINNER: '#109c00',
  LOSER:'#ad0014',
  ERROR:'#e30922'
};
export default Colors;

