const Colors = {
  GAME_BACKGROUND:"#1a1a1a",
  TITTLE_GAME:'#FFF',
  SQUARE_KEYBOARD_BACKGROUND:"#949494",
  SQUARE_KEYBOARD:'#FFF',
  // Cores possiveis dos quadrados das letras 
  ONFOCUS_STATUS_BACKGROUND:"#1a1a1a",
  ONFOCUS_STATUS_BORDER:'#FFF',
  DEFAULT_STATUS_BACKGROUND:"#1a1a1a",
  DEFAULT_STATUS_BORDER:'#3b3b3b',
  YELLOW_STATUS_BACKGROUND:"#ffb026",
  YELLOW_STATUS_BORDER:'#FFF',
  GREEN_STATUS_BACKGROUND:'#22a800',
  GREEN_STATUS_BORDER:'#1b7d02',
  RED_STATUS_BACKGROUND:'#b6bfb4',
  RED_STATUS_BORDER:"#949494",
  // Cores dos avisos
  TOAST_LABEL: '#FFF',
  ERROR:'#fc0f2b',
  SUCCESS:'#176b12',
};
export default Colors;